name: K6 Load Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run Load Test
      run: |
        k6 run tests/load-test.js  

  
